### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by lookapanda** [ui-router/react-hybrid#1]
>  Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

when using this package.

**Comment by christopherthielen** [comment]
This should be fixed by https://github.com/ui-router/react/commit/fd3bdb0f1f5006b31e756cc3f8b75b19d1625f8e#diff-4bd118d80c05a800e26fdc8c48bc6c65
