### ISSUE TITLE
TypeError: Cannot read property '$type' of undefined

### ISSUE THREAD

**Issue by hrgui** [ui-router/react-hybrid#10]
https://github.com/ui-router/react-hybrid/blob/master/src/decorateUIRouterViewConfigs.ts#L34
```javascript
.state('account.view.list', {
        url: '/list?new&updated&sortBy',
        title: title,
        views: {
          'sub_header@': accountRoutesHelperServiceProvider.getAccountDetails(),
          '': {templateUrl: 'someTemplate.html'}
```

```
 const view = views[key];
      const selfView = selfViews[key];
```

In views, it gets defined as '$default', but selfViews define it as ''; what is the expected behavior here? 

Is the state definition wrong: should I update it to '$default'? 

===
From https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views: 
```
     // Relatively targets the unnamed view in this state's parent state, 'contacts'.		
        // <div ui-view/> within contacts.html		
        "" : { }, 		
```	

https://github.com/angular-ui/ui-router/blob/b2b906b0ad45f06ed114b0c042bdc60a176c60a8/src/statebuilders/views.ts#L56

**Comment by kwalker3690** [comment]
We're also running into this issue, would love to know if the workaround prescribed here is the suggestion, or if this can be fixed within the repo itself.

**Comment by kwalker3690** [comment]
I'm not sure this was actually solved - as mentioned [here](https://github.com/ui-router/react-hybrid/commit/357989497190bcedf6b9a6ace9639f75bb9354e9) by the commit author, this relevant commit was somehow not merged: https://github.com/ui-router/react-hybrid/commit/323faf1f308d65a4524787c54b452edba32a676c#diff-27859f2b9609526b65d934ba68e2dbd1R35

I'm on v0.3.0 and still experiencing this issue. Please reopen the issue or share further context as to how it should remain closed! Thanks for the help in advance.
