### ISSUE TITLE
incompatible with React 16

### ISSUE THREAD

**Issue by christopherthielen** [ui-router/react-hybrid#12]

**Comment by hrgui** [comment]
That's interesting - because we have React 16 running fine with react-hybrid? 

Although there are some unmounting errors

**Comment by christopherthielen** [comment]
I'd like to see those errors.  

Here's a stackblitz set up with `@uirouter/react-hybrid` which shows at least one of the issues I've run across: https://stackblitz.com/edit/ui-router-react-hybrid-respce?file=index.js

**Comment by christopherthielen** [comment]
I've also [added the trivial example to this repo](https://github.com/ui-router/react-hybrid/tree/master/example) and wired it as an e2e test (`yarn test:downstream` -- requires [yalc](https://www.npmjs.com/package/yalc) installed globally)

**Comment by christopherthielen** [comment]
![screen shot 2018-03-10 at 10 47 52 am](https://user-images.githubusercontent.com/2053478/37245663-9558d880-2450-11e8-9d7a-3cb89c8f4308.png)

**Comment by christopherthielen** [comment]
going from `#!/angular/react` to `#!/angular`

![screen shot 2018-03-10 at 10 49 15 am](https://user-images.githubusercontent.com/2053478/37245684-c33122bc-2450-11e8-836d-666f73d359ab.png)

**Comment by hrgui** [comment]
https://github.com/ui-router/react-hybrid/issues/12#issuecomment-372054718 is the error that I encountered

I'm wondering if React is asking `@ui-router/react-hybrid` to do https://reactjs.org/docs/react-dom.html#unmountcomponentatnode on exit?

**Comment by christopherthielen** [comment]
This was the key: 

https://github.com/ui-router/react-hybrid/blob/f61e241be5ea3bd7ea74371405c10395d90d2e7d/src/angularjs/ReactUIViewAdapterComponent.tsx#L78-L81

**Comment by hrgui** [comment]
Interesting - the `ref` callback fires again when unMountComponentAtNode fires...

**Comment by christopherthielen** [comment]
> Interesting - the ref callback fires again when unMountComponentAtNode is called.



is that a problem though?  It gets called with `null` right?

**Comment by hrgui** [comment]
https://github.com/ui-router/react-hybrid/issues/12#issuecomment-372074109

Nope, it's not a problem, and yes it gets called with null:
https://github.com/facebook/react/blob/94518b068bf52196abea0c83f4c9926bfe2065c6/packages/react-reconciler/src/ReactFiberCommitWork.js#L136

Seems to be part of React Fiber.
