### ISSUE TITLE
React state components do not unmount / remount when stateTransition.reload(true) is called

### ISSUE THREAD

**Issue by mentierd** [ui-router/react-hybrid#14]
When you call `this.props.transition.router.stateService.reload(true)`, if the current state is a React component, the component is not "reloaded"; by that, I mean it does not unmount and remount the react component.

I've also tried the other approach of using `transitionTo(..., null, {reload:true, notify:true})`.

Maybe I'm missing something?

**Comment by christopherthielen** [comment]
No, you're not missing anything.  This is a limitation of the react ui-view.  I'm moving this issue to the react issue tracker.

**Comment by christopherthielen** [comment]
This issue was moved to ui-router/react#172
