### ISSUE TITLE
Apollo Client support

### ISSUE THREAD

**Issue by iliyan-trifonov** [ui-router/react-hybrid#144]
Hello guys!

I am new to `Apollo client` and I can see they use the `*Provider` pattern to activate `Apollo` for any `React` component in the tree. It's similar to how `Redux` is used.
However we have a hybrid `AngularJS`/`ReactJS` app and use your amazing router to be able to move to `React` incrementally but now we don't have `ReactDOM.render()` where I can add the ApolloProvider component and I wonder if we can still use `Apollo` with our configuration?

Thank you in advance for any hints! 👍 

PS: if you suggest using another `graphQL` client instead of `Apollo` I will be happy to investigate it.

**Comment by Anber** [comment]
Hi!
Just create a root react-state with Apollo and check that you use the latest version of react-hybrid.

**Comment by iliyan-trifonov** [comment]
Hi @Anber ! Thank you for your suggestion!
Some time passed since I asked here and these days I am using the `client` object more than the `<ApolloProvider>` and `<Query>` `<Mutation>` components.
For now `client.query()` and `client.mutation()` are enough for me but I will be back to the components way after I rewrite most of my code to React and get rid of AngularJS.
Thanks!
