### ISSUE TITLE
React directives don't work with hybrid app

### ISSUE THREAD

**Issue by iNishant** [ui-router/react-hybrid#28]
As mentioned in the readme, we should be able to use react directives in the react components. I am getting an error `UIRouter instance is undefined.` This is probably because ui-router (react) is not initialised. Is this the intended behaviour?  I am migrating my **Angular 1** project to **React** using **react2angular** by rewriting the angular components in react. The main app is still in Angular which uses ui-router (angular) for routing.

> When routing to a React component, that component can use the standard React directives (UIView, UISref, UISrefActive) from @uirouter/react.

**Comment by christopherthielen** [comment]
With `@uirouter/react` (not `react-hybrid`), the router is added to the react `context` [using the `UIRouter` react component](https://github.com/ui-router/react/blob/f16aed3c1d5493c3f45022f19449f1666b9272b4/examples/typescript/index.tsx#L58-L73).  With `react-hybrid`, the router is automatically added to the react context when you [route to a react component](https://github.com/ui-router/react-hybrid/blob/30b5d67c775b9be4368f1c107c13c67a8e4822d0/example/src/index.js#L8).  

This error may show up when you're routing to AngularJS, using `react2angular`  inside the angular component, and trying to use a `@uirouter/react` component such as `UIView` or `UISref`.  To work around this issue, you can *manually* add the router to the react context for any `react2angular` components that use things like `UISref`.

### Using UIRouterContextComponent

In your `react2angular` component that uses `UISref`, wrap in `<UIRouterContextComponent>`:

```js
const MyComponent = () => (
  <UIRouterContextComponent>
    <div>
      <UISref to="mystate">
        <a>mystate</a>
      </UISref>
    </div>
  </UIRouterContextComponent>
)

angular.component('myComponent', react2angular(MyComponent));
```

### Using `UIRouterContext` decorator

If you are using decorators (typescript or babel), you can decorate your component:

```js
@UIRouterContext
class MyComponent extends React.Component (
  render() {
    return (
    <div>
      <UISref to="mystate">
        <a>mystate</a>
      </UISref>
    </div>
    )
  }
}

angular.component('myComponent', react2angular(MyComponent));
```

**Comment by iNishant** [comment]
This works. Thanks. Missed this part of the Readme: https://github.com/ui-router/react-hybrid#providing-context-to-children .

**Comment by iNishant** [comment]
@christopherthielen The `UIView` directive doesn't seem to be working for me. The component is wrapped in `UIRouterContextComponent` but when the child state gets activated, it is not getting populated inside `UIView`. I created another issue https://github.com/ui-router/react-hybrid/issues/119 for this. Just want to know if I am making a silly mistake or the current version doesn't support nested `UIView`s

**Comment by iNishant** [comment]
Routing directly to the react component without `react2angular` solved it
