### ISSUE TITLE
When react component under UIView throws an error, the error runs an infinite loop

### ISSUE THREAD

**Issue by hrgui** [ui-router/react-hybrid#33]
**Stackblitz:**
https://stackblitz.com/edit/ui-router-react-hybrid-vgg4fy?file=ReactComponent.js
click on "react"

**PR demonstrates issue**
https://github.com/ui-router/react-hybrid/pull/32

**Comment by hrgui** [comment]
Some observations:
It seems `@uirouter/react` is calling `UIView.prototype.viewConfigUpdated`, which calls `setState`, which then tries to mount the component again - thus calling the ref.

However, React sees the error, then unmounts it.

Angular's digest cycle re-triggers `UIView.prototype.viewConfigUpdated`

**Comment by hrgui** [comment]
@christopherthielen any opinion on this? Currently as it stands, everytime an error occurs within ui-router/react-hybrid, it just crashes Chrome. If you have any other idea to workaround this, that would be great, as my browser just continues to crash on a daily basis when errors happen.

**Comment by christopherthielen** [comment]
@hrgu thanks.  I've been meaning to look at this, but haven't had much time lately.  I hope to look at it soon!
