### ISSUE TITLE
Route to state with params doesn't work

### ISSUE THREAD

**Issue by henrypoon** [ui-router/react-hybrid#73]
I am trying to route from react component and implemented as the way mentioned in
https://github.com/ui-router/react-hybrid/issues/28

It does work for normal state without params in url, however it seems doesn't work for the url with params. Console was showing the error of `stateService.js:41 Transition Rejection($id: 2 type: 6, message: The transition errored, detail: Error: Transition Rejection($id: 1 type: 4, message: This transition is invalid, detail: The following parameter values are not valid for state 'contact-detail': [id:"undefined"]))`  Here's how i implemented

Define state
```javascript
$stateProvider
  .state('contact', {
     url: '/contacts/:id',
     template: "<contact-detail></contact-detail>"
  })
```

in react component
```javascript
  <UIRouterContextComponent>
    <div>
      <UISref to={'contact'} params={{id: 1234}}>
        <a>hello world</a>
      </UISref>
    </div>
  </UIRouterContextComponent>
```

**Comment by henrypoon** [comment]
Solved, it just had a typo

**Comment by venkatgude90** [comment]
$stateProvider
.state('action', {
            url: 'action/:id',
            template: '<actionedit></actionedit>',
            params: {
                currentAction: null,
                locationUrl: null
            },
            requireADLogin: login
        })

Getting similar error as above. Can you please help me what was the typo that you have identified.
